version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11.0  # 使用するDockerイメージをPython 3.11に設定
    steps:
      - checkout  # リポジトリのコードをチェックアウト
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt  # 依存関係のインストール
      - run:
          name: Run tests
          command: python -m unittest discover -s test_app  # テストの実行

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
